# Homebrew cask for Screen-local Dock. Generated by scripts/release.sh from
# packaging/homebrew/screen-local-dock.rb.tmpl (version, sha256 and url filled
# in). The generated file goes into the public tap repo gee-m/homebrew-tap so
# `brew install --cask gee-m/tap/screen-local-dock` works. The tap is NOT created
# by any script here — see DISTRIBUTION.md.
cask "screen-local-dock" do
  version "0.3.1"
  sha256 "836c6c35da50655d85c6f470fea7140ab8f1040beb0eaa76606cc3a3085e6082"

  url "https://guillaume.ai/downloads/ScreenLocalDock-0.3.1.dmg"
  name "Screen-local Dock"
  desc "Per-display dock of the windows on that screen, summoned by a wiggle"
  homepage "https://guillaume.ai/apps"

  # Ad-hoc signed for now, so the download carries the quarantine flag. Sparkle
  # keeps it current after the first install; `auto_updates true` tells Homebrew
  # not to fight it.
  auto_updates true
  depends_on macos: :ventura

  app "ScreenLocalDock.app"

  zap trash: [
    "~/Library/Preferences/co.merindol.screenlocaldock.plist",
  ]
end
